apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-example
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/alileza/crossplane-example.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m