---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresql-role
  namespace: platform
rules:
- apiGroups: ["sql.crossplane.io"]
  resources: ["databases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-rolebinding
  namespace: platform
roleRef:
  kind: Role
  name: postgresql-role
  apiGroup: rbac.authorization.k8s.io

# resource postgresql.sql.crossplane.io:Database is not permitted in project platform