apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: d-product-vpc
spec:
  deletionPolicy: Delete
  forProvider:
    region: me-south-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: aws-provider-config
