apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: sql-provider-config
  namespace: crossplane-system
spec:
  credentials:
    connectionSecretRef:
      name: example-secret
      namespace: platform
    source: PostgreSQLConnectionSecret
  sslMode: disable
  defaultDatabase: mydb
